Space Travelers' Hub: Rockets, Missions, and Profile Integration
egichuhis/space-travelers-hub pull request #38
Opened 2023-10-05 15:00 UTC by egichuhis

Hello,

Please review this pull request for the Space Travelers' Hub project. This collaborative effort between @egichuhis and @erickma1 introduces several significant changes:

1. Rockets Section: Displays a list of available SpaceX rockets with booking and cancellation functionality.
2. Missions Section: Presents a list of current missions, enabling users to join or leave missions.
3. My Profile Section: Showcases reserved rockets and joined missions.
4. Redux Integration: Fetches data from the SpaceX API and updates the Redux store.
5. Redux Actions and Reducers: Implemented for booking rockets and joining missions.

2023-10-05 16:38 UTC, Gambit142 requested changes
Hi @egichuhis @erickma1 👋, 

Good job so far!

## Highlights
- Setup linters correctly ✔️ 
- Fetched data from API ✔️ 
- Setup redux store using `@reduxjs/toolkit` ✔️ 
- Rendered missions and rockets ✔️ 
- Use of `Jest` and `React Testing Library` ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-10-05 16:38 UTC, Gambit142 commented on src/components/Missions/Missions.jsx
> +
- [ ] One of the major requirements for this project is that you dispatch the actions that fetch the _**rockets**_ and _**missions**_ once and not on every re-render for optimization purposes. Whenever I click the navigation links for the _**rockets**_ or the **_mission_**, I notice that the actions are dispatched again and the reservations/missions joined that I have are no longer available. Please ensure that the actions are dispatched once.

#### Hint: Kindly dispatch the actions in the `App` component. 👍 😎

2023-10-05 16:38 UTC, Gambit142 commented on src/components/Rockets/RocketsList.jsx
> +
- [ ] One of the major requirements for this project is that you dispatch the actions that fetch the _**rockets**_ and _**missions**_ once and not on every re-render for optimization purposes. Whenever I click the navigation links for the _**rockets**_ or the **_mission_**, I notice that the actions are dispatched again and the reservations/missions joined that I have are no longer available. Please ensure that the actions are dispatched once.

#### Hint: Kindly dispatch the actions in the `App` component. 👍 😎

2023-10-05 17:56 UTC, Alusp approved these changes
Hi @egichuhis and @erickma1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![congrats](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)

## Highlights

- [ ] Setup linters correctly ✔️
- [ ] Fetched data from API ✔️
- [ ] Setup redux store using @reduxjs/toolkit ✔️
- [ ] Rendered missions and rockets ✔️
- [ ] Use of Jest and React Testing Library ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-05 17:56 UTC, Alusp commented on src/components/Layout/NavBar.jsx
> +        </a>
- [OPTIONAL BUT HIGHLY RECOMMENDED] Please ensure that you replace your `a` tag with `Link` and replace the `href` with `to` in your Nav component, because whenever I click on the home page icon your app rerenders and clears all the existing data. :slightly_smiling_face:

2023-10-06 06:10 UTC, egichuhis commented on src/components/Layout/NavBar.jsx
> +        </a>
Thanks for this tip @Alusp ! 🥳

2023-10-06 06:10 UTC, merged

2023-10-06 09:44 UTC, Alusp commented on src/components/Layout/NavBar.jsx
> +        </a>
You are most welcome @egichuhis